In [1]:
from datetime import datetime

In [41]:
import pandas as pd

In [108]:
data=pd.read_excel('C:/Users/user/Downloads/한남_진재.xlsx')

In [43]:
import datetime

In [109]:
a=pd.to_datetime(data['인허가일자'])

In [110]:
b=pd.to_datetime(data['폐업일자'])

In [30]:
from datetime import datetime, timedelta

In [134]:
c=[]
for i in range(len(a)):
    if b[i]<pd.Timestamp(2011,1,1) or a[i]>pd.Timestamp(2019,12,31):
        c.append(None)
    elif a[i]<=pd.Timestamp(2011,1,1)  and b[i]>=pd.Timestamp(2019,12,31):
        c.append(pd.Timestamp(2019,12,31)-pd.Timestamp(2011,1,1))
    elif a[i]>pd.Timestamp(2011,1,1)  and  b[i]>=pd.Timestamp(2019,12,31):
        c.append(pd.Timestamp(2019,12,31)-a[i])
    elif a[i]>=pd.Timestamp(2011,1,1)  and  b[i]<pd.Timestamp(2019,12,31) :
        c.append(b[i]-a[i])
    elif a[i]<pd.Timestamp(2011,1,1)  and  b[i]>pd.Timestamp(2019,12,31):
        c.append(b[i]-pd.Timestamp(2011,1,1))
    else:
        c.append(pd.Timestamp(2019,12,31)-a[i])
           
data['영업일']=c

In [135]:
c

[None,
 None,
 Timedelta('428 days 00:00:00'),
 Timedelta('172 days 00:00:00'),
 None,
 Timedelta('414 days 00:00:00'),
 Timedelta('243 days 00:00:00'),
 Timedelta('516 days 00:00:00'),
 Timedelta('496 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('383 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('12408 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('211 days 00:00:00'),
 Timedelta('243 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('10728 days 00:00:00'),
 None,
 Timedelta('2951 days 00:00:00'),
 None,
 None,
 Timedelta('7395 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('10118 days 00:00:00'),
 Timedelta('930 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('869 days 00:00:00'),
 None,
 Timedelta('12662 days 00:00:00'),
 None,
 Timedelta('852 days 00:00:00'),
 Timedelta('1064 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('6370 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('6598 days 00:00:00'),
 None,
 Timedelta('6019 days 00:00:00'),
 Timedelta('110 days 00:00:00'),
 Timedelta('104 days 00:00:00'),
 Timedelta('76 days 00:00:00'),
 Timedelta('6752 days 00:00:00'),
 None,
 Timedelta('5757 days 00:00:00'),
 None,
 None,
 Timedelta('6752 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('6838 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('6816 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('4064 days 00:00:00'),
 None,
 Timedelta('5865 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('6606 days 00:00:00'),
 None,
 Timedelta('6290 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('6123 days 00:00:00'),
 None,
 None,
 Timedelta('6406 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 Timedelta('6609 days 00:00:00'),
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('5771 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('6649 days 00:00:00'),
 None,
 Timedelta('6653 days 00:00:00'),
 Timedelta('6467 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('4334 days 00:00:00'),
 Timedelta('4066 days 00:00:00'),
 Timedelta('6461 days 00:00:00'),
 Timedelta('6185 days 00:00:00'),
 Timedelta('6185 days 00:00:00'),
 None,
 None,
 Timedelta('6636 days 00:00:00'),
 Timedelta('6560 days 00:00:00'),
 Timedelta('4135 days 00:00:00'),
 Timedelta('6276 days 00:00:00'),
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('6237 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('6412 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('4019 days 00:00:00'),
 None,
 Timedelta('4030 days 00:00:00'),
 Timedelta('4241 days 00:00:00'),
 Timedelta('203 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('6783 days 00:00:00'),
 None,
 None,
 Timedelta('4369 days 00:00:00'),
 Timedelta('4376 days 00:00:00'),
 None,
 None,
 Timedelta('6455 days 00:00:00'),
 Timedelta('4089 days 00:00:00'),
 Timedelta('4347 days 00:00:00'),
 Timedelta('5860 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('1428 days 00:00:00'),
 Timedelta('4261 days 00:00:00'),
 Timedelta('4264 days 00:00:00'),
 None,
 Timedelta('4248 days 00:00:00'),
 None,
 Timedelta('6058 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('5886 days 00:00:00'),
 Timedelta('817 days 00:00:00'),
 Timedelta('957 days 00:00:00'),
 Timedelta('1504 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1043 days 00:00:00'),
 Timedelta('568 days 00:00:00'),
 Timedelta('4430 days 00:00:00'),
 Timedelta('1183 days 00:00:00'),
 Timedelta('853 days 00:00:00'),
 Timedelta('1226 days 00:00:00'),
 Timedelta('507 days 00:00:00'),
 None,
 Timedelta('1215 days 00:00:00'),
 Timedelta('56 days 00:00:00'),
 Timedelta('1051 days 00:00:00'),
 Timedelta('4436 days 00:00:00'),
 Timedelta('64 days 00:00:00'),
 Timedelta('1148 days 00:00:00'),
 Timedelta('372 days 00:00:00'),
 Timedelta('943 days 00:00:00'),
 Timedelta('112 days 00:00:00'),
 Timedelta('1215 days 00:00:00'),
 Timedelta('830 days 00:00:00'),
 Timedelta('960 days 00:00:00'),
 Timedelta('664 days 00:00:00'),
 None,
 None,
 Timedelta('914 days 00:00:00'),
 None,
 Timedelta('5887 days 00:00:00'),
 None,
 None,
 Timedelta('886 days 00:00:00'),
 Timedelta('1148 days 00:00:00'),
 Timedelta('1376 days 00:00:00'),
 Timedelta('543 days 00:00:00'),
 Timedelta('243 days 00:00:00'),
 Timedelta('656 days 00:00:00'),
 None,
 Timedelta('5909 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('62 days 00:00:00'),
 None,
 Timedelta('190 days 00:00:00'),
 Timedelta('393 days 00:00:00'),
 Timedelta('186 days 00:00:00'),
 Timedelta('440 days 00:00:00'),
 None,
 Timedelta('748 days 00:00:00'),
 Timedelta('444 days 00:00:00'),
 Timedelta('174 days 00:00:00'),
 Timedelta('416 days 00:00:00'),
 Timedelta('854 days 00:00:00'),
 Timedelta('4473 days 00:00:00'),
 Timedelta('823 days 00:00:00'),
 Timedelta('41 days 00:00:00'),
 Timedelta('1110 days 00:00:00'),
 Timedelta('733 days 00:00:00'),
 None,
 None,
 Timedelta('1089 days 00:00:00'),
 Timedelta('470 days 00:00:00'),
 Timedelta('1058 days 00:00:00'),
 Timedelta('15 days 00:00:00'),
 Timedelta('1302 days 00:00:00'),
 Timedelta('860 days 00:00:00'),
 Timedelta('56 days 00:00:00'),
 Timedelta('995 days 00:00:00'),
 Timedelta('413 days 00:00:00'),
 Timedelta('652 days 00:00:00'),
 Timedelta('1344 days 00:00:00'),
 Timedelta('831 days 00:00:00'),
 Timedelta('673 days 00:00:00'),
 Timedelta('1345 days 00:00:00'),
 Timedelta('419 days 00:00:00'),
 Timedelta('5916 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('6888 days 00:00:00'),
 Timedelta('663 days 00:00:00'),
 Timedelta('846 days 00:00:00'),
 Timedelta('614 days 00:00:00'),
 Timedelta('615 days 00:00:00'),
 Timedelta('99 days 00:00:00'),
 Timedelta('95 days 00:00:00'),
 Timedelta('175 days 00:00:00'),
 None,
 Timedelta('153 days 00:00:00'),
 Timedelta('1373 days 00:00:00'),
 Timedelta('767 days 00:00:00'),
 Timedelta('459 days 00:00:00'),
 Timedelta('805 days 00:00:00'),
 Timedelta('1456 days 00:00:00'),
 Timedelta('475 days 00:00:00'),
 Timedelta('717 days 00:00:00'),
 Timedelta('276 days 00:00:00'),
 Timedelta('399 days 00:00:00'),
 Timedelta('378 days 00:00:00'),
 Timedelta('788 days 00:00:00'),
 Timedelta('395 days 00:00:00'),
 Timedelta('988 days 00:00:00'),
 Timedelta('711 days 00:00:00'),
 Timedelta('711 days 00:00:00'),
 Timedelta('734 days 00:00:00'),
 Timedelta('1254 days 00:00:00'),
 Timedelta('435 days 00:00:00'),
 Timedelta('490 days 00:00:00'),
 Timedelta('629 days 00:00:00'),
 Timedelta('606 days 00:00:00'),
 Timedelta('707 days 00:00:00'),
 None,
 None,
 Timedelta('5453 days 00:00:00'),
 None,
 None,
 Timedelta('617 days 00:00:00'),
 Timedelta('617 days 00:00:00'),
 Timedelta('799 days 00:00:00'),
 Timedelta('796 days 00:00:00'),
 Timedelta('799 days 00:00:00'),
 None,
 None,
 Timedelta('9909 days 00:00:00'),
 Timedelta('4562 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1786 days 00:00:00'),
 None,
 None,
 Timedelta('365 days 00:00:00'),
 Timedelta('1975 days 00:00:00'),
 None,
 Timedelta('945 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('689 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('9346 days 00:00:00'),
 None,
 Timedelta('985 days 00:00:00'),
 Timedelta('1861 days 00:00:00'),
 Timedelta('1861 days 00:00:00'),
 None,
 Timedelta('9306 days 00:00:00'),
 Timedelta('573 days 00:00:00'),
 None,
 None,
 Timedelta('1008 days 00:00:00'),
 None,
 Timedelta('2090 days 00:00:00'),
 None,
 None,
 Timedelta('4606 days 00:00:00'),
 Timedelta('4746 days 00:00:00'),
 Timedelta('2230 days 00:00:00'),
 Timedelta('299 days 00:00:00'),
 Timedelta('13 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('556 days 00:00:00'),
 None,
 None,
 Timedelta('803 days 00:00:00'),
 Timedelta('702 days 00:00:00'),
 Timedelta('1947 days 00:00:00'),
 None,
 Timedelta('399 days 00:00:00'),
 None,
 None,
 Timedelta('9524 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('2080 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('837 days 00:00:00'),
 None,
 None,
 Timedelta('260 days 00:00:00'),
 None,
 Timedelta('9369 days 00:00:00'),
 Timedelta('5135 days 00:00:00'),
 Timedelta('440 days 00:00:00'),
 Timedelta('7141 days 00:00:00'),
 Timedelta('9393 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('727 days 00:00:00'),
 None,
 Timedelta('1498 days 00:00:00'),
 None,
 None,
 Timedelta('5059 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('135 days 00:00:00'),
 Timedelta('1855 days 00:00:00'),
 Timedelta('382 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('5009 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('2038 days 00:00:00'),
 Timedelta('5020 days 00:00:00'),
 Timedelta('911 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('2085 days 00:00:00'),
 Timedelta('2148 days 00:00:00'),
 Timedelta('9785 days 00:00:00'),
 Timedelta('5163 days 00:00:00'),
 Timedelta('1881 days 00:00:00'),
 Timedelta('4974 days 00:00:00'),
 Timedelta('2069 days 00:00:00'),
 Timedelta('1735 days 00:00:00'),
 None,
 None,
 Timedelta('986 days 00:00:00'),
 Timedelta('4772 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('1200 days 00:00:00'),
 Timedelta('2316 days 00:00:00'),
 Timedelta('2216 days 00:00:00'),
 Timedelta('4940 days 00:00:00'),
 Timedelta('988 days 00:00:00'),
 None,
 Timedelta('2134 days 00:00:00'),
 Timedelta('1288 days 00:00:00'),
 Timedelta('1736 days 00:00:00'),
 Timedelta('1736 days 00:00:00'),
 None,
 Timedelta('833 days 00:00:00'),
 Timedelta('1379 days 00:00:00'),
 Timedelta('1902 days 00:00:00'),
 None,
 Timedelta('995 days 00:00:00'),
 Timedelta('1491 days 00:00:00'),
 Timedelta('1491 days 00:00:00'),
 None,
 Timedelta('4990 days 00:00:00'),
 Timedelta('1993 days 00:00:00'),
 Timedelta('2055 days 00:00:00'),
 Timedelta('1093 days 00:00:00'),
 Timedelta('1310 days 00:00:00'),
 Timedelta('1414 days 00:00:00'),
 Timedelta('67 days 00:00:00'),
 Timedelta('365 days 00:00:00'),
 Timedelta('4675 days 00:00:00'),
 None,
 Timedelta('1005 days 00:00:00'),
 Timedelta('568 days 00:00:00'),
 None,
 Timedelta('979 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1001 days 00:00:00'),
 None,
 Timedelta('1243 days 00:00:00'),
 Timedelta('272 days 00:00:00'),
 None,
 Timedelta('719 days 00:00:00'),
 Timedelta('4866 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('2232 days 00:00:00'),
 Timedelta('837 days 00:00:00'),
 None,
 None,
 Timedelta('1414 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1481 days 00:00:00'),
 Timedelta('771 days 00:00:00'),
 Timedelta('1783 days 00:00:00'),
 Timedelta('4757 days 00:00:00'),
 None,
 None,
 Timedelta('487 days 00:00:00'),
 Timedelta('2077 days 00:00:00'),
 Timedelta('889 days 00:00:00'),
 None,
 Timedelta('9489 days 00:00:00'),
 None,
 Timedelta('1667 days 00:00:00'),
 None,
 None,
 Timedelta('4773 days 00:00:00'),
 Timedelta('1623 days 00:00:00'),
 Timedelta('610 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('4996 days 00:00:00'),
 None,
 Timedelta('1496 days 00:00:00'),
 Timedelta('276 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1158 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('553 days 00:00:00'),
 Timedelta('1254 days 00:00:00'),
 Timedelta('204 days 00:00:00'),
 Timedelta('1232 days 00:00:00'),
 Timedelta('2081 days 00:00:00'),
 None,
 None,
 Timedelta('1608 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1918 days 00:00:00'),
 Timedelta('2751 days 00:00:00'),
 None,
 Timedelta('3343 days 00:00:00'),
 Timedelta('1059 days 00:00:00'),
 Timedelta('3331 days 00:00:00'),
 Timedelta('3465 days 00:00:00'),
 Timedelta('12597 days 00:00:00'),
 Timedelta('1693 days 00:00:00'),
 Timedelta('3406 days 00:00:00'),
 None,
 None,
 Timedelta('3122 days 00:00:00'),
 Timedelta('2325 days 00:00:00'),
 Timedelta('2619 days 00:00:00'),
 None,
 Timedelta('3640 days 00:00:00'),
 Timedelta('1538 days 00:00:00'),
 None,
 Timedelta('990 days 00:00:00'),
 Timedelta('2622 days 00:00:00'),
 Timedelta('1190 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('2778 days 00:00:00'),
 Timedelta('3480 days 00:00:00'),
 Timedelta('3422 days 00:00:00'),
 None,
 Timedelta('1260 days 00:00:00'),
 Timedelta('3487 days 00:00:00'),
 Timedelta('3487 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1734 days 00:00:00'),
 Timedelta('5129 days 00:00:00'),
 Timedelta('3428 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('2843 days 00:00:00'),
 None,
 Timedelta('3745 days 00:00:00'),
 None,
 None,
 Timedelta('509 days 00:00:00'),
 None,
 Timedelta('3528 days 00:00:00'),
 Timedelta('2100 days 00:00:00'),
 None,
 Timedelta('9891 days 00:00:00'),
 Timedelta('1996 days 00:00:00'),
 None,
 Timedelta('1317 days 00:00:00'),
 Timedelta('423 days 00:00:00'),
 Timedelta('3400 days 00:00:00'),
 Timedelta('3534 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('371 days 00:00:00'),
 Timedelta('350 days 00:00:00'),
 Timedelta('1622 days 00:00:00'),
 None,
 Timedelta('4960 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 Timedelta('270 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1369 days 00:00:00'),
 Timedelta('819 days 00:00:00'),
 Timedelta('952 days 00:00:00'),
 Timedelta('941 days 00:00:00'),
 Timedelta('2900 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('1959 days 00:00:00'),
 Timedelta('1342 days 00:00:00'),
 Timedelta('2156 days 00:00:00'),
 Timedelta('358 days 00:00:00'),
 None,
 Timedelta('1386 days 00:00:00'),
 Timedelta('1908 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('4632 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1943 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('548 days 00:00:00'),
 Timedelta('2495 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('252 days 00:00:00'),
 Timedelta('275 days 00:00:00'),
 None,
 None,
 Timedelta('640 days 00:00:00'),
 Timedelta('9397 days 00:00:00'),
 Timedelta('1726 days 00:00:00'),
 Timedelta('1814 days 00:00:00'),
 None,
 None,
 Timedelta('4954 days 00:00:00'),
 Timedelta('616 days 00:00:00'),
 Timedelta('623 days 00:00:00'),
 Timedelta('2037 days 00:00:00'),
 Timedelta('658 days 00:00:00'),
 Timedelta('1727 days 00:00:00'),
 Timedelta('2420 days 00:00:00'),
 Timedelta('529 days 00:00:00'),
 Timedelta('5128 days 00:00:00'),
 None,
 None,
 Timedelta('1174 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1287 days 00:00:00'),
 Timedelta('3774 days 00:00:00'),
 None,
 None,
 Timedelta('747 days 00:00:00'),
 Timedelta('5009 days 00:00:00'),
 Timedelta('4767 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('7865 days 00:00:00'),
 Timedelta('7916 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('1055 days 00:00:00'),
 Timedelta('1664 days 00:00:00'),
 Timedelta('350 days 00:00:00'),
 Timedelta('427 days 00:00:00'),
 Timedelta('898 days 00:00:00'),
 Timedelta('2988 days 00:00:00'),
 Timedelta('1834 days 00:00:00'),
 None,
 Timedelta('4722 days 00:00:00'),
 Timedelta('2137 days 00:00:00'),
 Timedelta('314 days 00:00:00'),
 None,
 Timedelta('537 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('444 days 00:00:00'),
 Timedelta('2605 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('5284 days 00:00:00'),
 Timedelta('1671 days 00:00:00'),
 Timedelta('1358 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('5254 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('8631 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('382 days 00:00:00'),
 Timedelta('7669 days 00:00:00'),
 Timedelta('1432 days 00:00:00'),
 None,
 None,
 Timedelta('5320 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('7204 days 00:00:00'),
 None,
 None,
 Timedelta('91 days 00:00:00'),
 Timedelta('475 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('7651 days 00:00:00'),
 None,
 Timedelta('918 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('438 days 00:00:00'),
 Timedelta('1580 days 00:00:00'),
 Timedelta('1144 days 00:00:00'),
 Timedelta('1059 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('317 days 00:00:00'),
 None,
 None,
 Timedelta('7477 days 00:00:00'),
 None,
 Timedelta('7330 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('7 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('8735 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('452 days 00:00:00'),
 Timedelta('532 days 00:00:00'),
 Timedelta('1637 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1421 days 00:00:00'),
 Timedelta('7281 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('7097 days 00:00:00'),
 Timedelta('5360 days 00:00:00'),
 None,
 None,
 Timedelta('317 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('7781 days 00:00:00'),
 None,
 None,
 Timedelta('5319 days 00:00:00'),
 None,
 None,
 Timedelta('7216 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('7168 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('788 days 00:00:00'),
 Timedelta('876 days 00:00:00'),
 None,
 None,
 Timedelta('7560 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('7486 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('50 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('13557 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1888 days 00:00:00'),
 Timedelta('720 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('7223 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('7432 days 00:00:00'),
 Timedelta('7692 days 00:00:00'),
 None,
 None,
 Timedelta('778 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('13175 days 00:00:00'),
 Timedelta('2108 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1821 days 00:00:00'),
 Timedelta('720 days 00:00:00'),
 Timedelta('15298 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('203 days 00:00:00'),
 Timedelta('196 days 00:00:00'),
 None,
 None,
 Timedelta('7798 days 00:00:00'),
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('2426 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1642 days 00:00:00'),
 None,
 Timedelta('203 days 00:00:00'),
 Timedelta('295 days 00:00:00'),
 Timedelta('234 days 00:00:00'),
 Timedelta('210 days 00:00:00'),
 Timedelta('256 days 00:00:00'),
 Timedelta('3557 days 00:00:00'),
 None,
 None,
 Timedelta('8954 days 00:00:00'),
 Timedelta('3477 days 00:00:00'),
 ...]

In [112]:
data

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,인허가일자,영업상태명,폐업일자,영업일,동,소재지전체주소,도로명전체주소,...,경도,위도,distance to intersection,land use type,가장 가까운 버스장류장까지 거리,가장 가까운 공원까지 거리,distance to station(m),레스토랑 규모 성장률,reatil_성장률,house_성장률
0,0,0,0,2020-12-09,폐업,2022-01-21,NaT,한남동,서울특별시 용산구 한남동 743-5 170523,"서울특별시 용산구 이태원로49길 24-12, 3층 (한남동)",...,126.996646,37.537364,1900-08-23 16:47:43.761,1,296.059362,627.476873,380.815222,NaN,0.000000,0.0
1,1,1,1,2020-09-14,폐업,2022-03-25,NaT,한남동,서울특별시 용산구 한남동 87-7,"서울특별시 용산구 대사관로34길 13, 2층 (한남동)",...,127.003339,37.532592,1900-03-24 16:59:34.747,2,155.288207,831.432692,622.782809,NaN,0.000000,0.0
2,2,2,2,2018-10-29,폐업,2019-12-31,428 days,한남동,서울특별시 용산구 한남동 72-17번지 언고오피스텔 101-3호,"서울특별시 용산구 독서당로 65-3, 언고오피스텔 1층 101-3호 (한남동)",...,127.005037,37.533974,1900-05-25 16:19:15.927,1,73.286265,657.517752,622.973239,-1.130875,-5.937066,1.6
3,3,3,3,2018-12-10,폐업,2019-05-31,172 days,한남동,"서울특별시 용산구 한남동 96-3번지 신성미소시티 1층 107-2,107-4호","서울특별시 용산구 독서당로 39, 1층 107-2,107-4호 (한남동, 신성미소시티)",...,127.004227,37.531517,1900-07-29 13:12:23.628,1,184.050231,797.160783,493.752353,-1.130875,-5.937066,1.6
4,4,4,4,2020-12-02,폐업,2021-12-16,NaT,한남동,서울특별시 용산구 한남동 738-36,"서울특별시 용산구 이태원로 241, 1층 (한남동)",...,126.997029,37.536647,1900-05-29 18:51:29.933,1,217.441593,646.400904,339.774479,NaN,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,2080,2080,2080,2019-03-21,영업/정상,NaT,NaT,한남동,서울특별시 용산구 한남동 683-49번지,"서울특별시 용산구 이태원로54길 52, 2층 (한남동)",...,126.998316,37.536228,1900-05-05 14:47:01.740,1,137.451800,754.501519,403.368149,0.000000,0.000000,0.0
2081,2081,2081,2081,2019-03-20,영업/정상,NaT,NaT,한남동,서울특별시 용산구 한남동 738-14번지,"서울특별시 용산구 이태원로45길 8, 1층 (한남동)",...,126.996295,37.536274,1900-05-24 08:17:00.071,1,177.483626,577.194534,265.202600,0.000000,0.000000,0.0
2082,2082,2082,2082,2019-03-27,영업/정상,NaT,NaT,한남동,서울특별시 용산구 한남동 739-28번지,"서울특별시 용산구 이태원로55길 11, 1층,지하1층호 (한남동)",...,126.997950,37.538218,1900-10-17 03:25:56.107,1,262.419355,661.749765,368.096419,0.000000,0.000000,0.0
2083,2083,2083,2083,2019-03-29,영업/정상,NaT,NaT,한남동,서울특별시 용산구 한남동 732-150번지 대한당약국,"서울특별시 용산구 우사단로10길 41, 대한당약국 1층 (한남동)",...,126.995119,37.533007,1900-11-24 04:06:50.150,1,52.148335,564.314067,179.768778,0.000000,0.000000,0.0
2084,2084,2084,2084,2019-03-29,영업/정상,NaT,NaT,한남동,서울특별시 용산구 한남동 684-67번지,"서울특별시 용산구 이태원로54길 63, 1층 (한남동)",...,126.998327,37.535696,1900-03-28 16:01:24.302,1,78.353264,754.022363,379.463282,0.000000,0.000000,0.0

In [136]:
data.isna().sum()

Unnamed: 0                    0
Unnamed: 0.1                  0
Unnamed: 0.1.1                0
인허가일자                         0
영업상태명                         0
폐업일자                          0
영업일                         954
동                             0
소재지전체주소                       0
도로명전체주소                     822
사업장명                          0
업태구분명                         0
좌표정보(X)                       0
좌표정보(Y)                       0
시설총규모                         0
경도                            0
위도                            0
distance to intersection      0
land use type                 0
가장 가까운 버스장류장까지 거리             0
가장 가까운 공원까지 거리                0
distance to station(m)        0
레스토랑 규모 성장률                 954
reatil_성장률                    0
house_성장률                     0
dtype: int64

In [137]:
len(data)

2085

In [138]:
data3=data.dropna(subset=['영업일'])

In [140]:
len(data3)

1131

In [141]:
data3

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,인허가일자,영업상태명,폐업일자,영업일,동,소재지전체주소,도로명전체주소,...,경도,위도,distance to intersection,land use type,가장 가까운 버스장류장까지 거리,가장 가까운 공원까지 거리,distance to station(m),레스토랑 규모 성장률,reatil_성장률,house_성장률
2,2,2,2,2018-10-29,폐업,2019-12-31,428 days,한남동,서울특별시 용산구 한남동 72-17번지 언고오피스텔 101-3호,"서울특별시 용산구 독서당로 65-3, 언고오피스텔 1층 101-3호 (한남동)",...,127.005037,37.533974,1900-05-25 16:19:15.927,1,73.286265,657.517752,622.973239,-1.130875,-5.937066,1.6
3,3,3,3,2018-12-10,폐업,2019-05-31,172 days,한남동,"서울특별시 용산구 한남동 96-3번지 신성미소시티 1층 107-2,107-4호","서울특별시 용산구 독서당로 39, 1층 107-2,107-4호 (한남동, 신성미소시티)",...,127.004227,37.531517,1900-07-29 13:12:23.628,1,184.050231,797.160783,493.752353,-1.130875,-5.937066,1.6
5,5,5,5,2018-11-12,폐업,2020-01-22,414 days,한남동,서울특별시 용산구 한남동 737-37번지 한남빌딩 1층,"서울특별시 용산구 이태원로 211, 한남빌딩 1층 (한남동)",...,126.994263,37.535028,1900-10-07 14:56:50.202,1,122.816592,404.815292,60.145673,-1.130875,-5.937066,1.6
6,6,6,6,2018-08-03,폐업,2019-04-03,243 days,한남동,서울특별시 용산구 한남동 828번지 한남아이파크 지1층 1호,"서울특별시 용산구 독서당로 46, 지1층 1호 (한남동, 한남아이파크)",...,127.004367,37.532391,1900-05-07 10:38:14.666,2,112.709155,750.620252,536.432897,-1.130875,-5.937066,1.6
7,7,7,7,2018-08-02,폐업,2022-05-30,516 days,한남동,서울특별시 용산구 한남동 636-7 3층,"서울특별시 용산구 대사관로 64, 3층 (한남동)",...,127.002249,37.533206,1900-04-08 02:40:59.193,1,188.961822,911.926523,715.057303,-1.130875,-5.937066,1.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2080,2080,2080,2080,2019-03-21,영업/정상,NaT,285 days,한남동,서울특별시 용산구 한남동 683-49번지,"서울특별시 용산구 이태원로54길 52, 2층 (한남동)",...,126.998316,37.536228,1900-05-05 14:47:01.740,1,137.451800,754.501519,403.368149,0.000000,0.000000,0.0
2081,2081,2081,2081,2019-03-20,영업/정상,NaT,286 days,한남동,서울특별시 용산구 한남동 738-14번지,"서울특별시 용산구 이태원로45길 8, 1층 (한남동)",...,126.996295,37.536274,1900-05-24 08:17:00.071,1,177.483626,577.194534,265.202600,0.000000,0.000000,0.0
2082,2082,2082,2082,2019-03-27,영업/정상,NaT,279 days,한남동,서울특별시 용산구 한남동 739-28번지,"서울특별시 용산구 이태원로55길 11, 1층,지하1층호 (한남동)",...,126.997950,37.538218,1900-10-17 03:25:56.107,1,262.419355,661.749765,368.096419,0.000000,0.000000,0.0
2083,2083,2083,2083,2019-03-29,영업/정상,NaT,277 days,한남동,서울특별시 용산구 한남동 732-150번지 대한당약국,"서울특별시 용산구 우사단로10길 41, 대한당약국 1층 (한남동)",...,126.995119,37.533007,1900-11-24 04:06:50.150,1,52.148335,564.314067,179.768778,0.000000,0.000000,0.0
2084,2084,2084,2084,2019-03-29,영업/정상,NaT,277 days,한남동,서울특별시 용산구 한남동 684-67번지,"서울특별시 용산구 이태원로54길 63, 1층 (한남동)",...,126.998327,37.535696,1900-03-28 16:01:24.302,1,78.353264,754.022363,379.463282,0.000000,0.000000,0.0

In [143]:
c

[None,
 None,
 Timedelta('428 days 00:00:00'),
 Timedelta('172 days 00:00:00'),
 None,
 Timedelta('414 days 00:00:00'),
 Timedelta('243 days 00:00:00'),
 Timedelta('516 days 00:00:00'),
 Timedelta('496 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('383 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('12408 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('211 days 00:00:00'),
 Timedelta('243 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('10728 days 00:00:00'),
 None,
 Timedelta('2951 days 00:00:00'),
 None,
 None,
 Timedelta('7395 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('10118 days 00:00:00'),
 Timedelta('930 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('869 days 00:00:00'),
 None,
 Timedelta('12662 days 00:00:00'),
 None,
 Timedelta('852 days 00:00:00'),
 Timedelta('1064 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('6370 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('6598 days 00:00:00'),
 None,
 Timedelta('6019 days 00:00:00'),
 Timedelta('110 days 00:00:00'),
 Timedelta('104 days 00:00:00'),
 Timedelta('76 days 00:00:00'),
 Timedelta('6752 days 00:00:00'),
 None,
 Timedelta('5757 days 00:00:00'),
 None,
 None,
 Timedelta('6752 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('6838 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('6816 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('4064 days 00:00:00'),
 None,
 Timedelta('5865 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('6606 days 00:00:00'),
 None,
 Timedelta('6290 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('6123 days 00:00:00'),
 None,
 None,
 Timedelta('6406 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 Timedelta('6609 days 00:00:00'),
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('5771 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('6649 days 00:00:00'),
 None,
 Timedelta('6653 days 00:00:00'),
 Timedelta('6467 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('4334 days 00:00:00'),
 Timedelta('4066 days 00:00:00'),
 Timedelta('6461 days 00:00:00'),
 Timedelta('6185 days 00:00:00'),
 Timedelta('6185 days 00:00:00'),
 None,
 None,
 Timedelta('6636 days 00:00:00'),
 Timedelta('6560 days 00:00:00'),
 Timedelta('4135 days 00:00:00'),
 Timedelta('6276 days 00:00:00'),
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('6237 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('6412 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('4019 days 00:00:00'),
 None,
 Timedelta('4030 days 00:00:00'),
 Timedelta('4241 days 00:00:00'),
 Timedelta('203 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('6783 days 00:00:00'),
 None,
 None,
 Timedelta('4369 days 00:00:00'),
 Timedelta('4376 days 00:00:00'),
 None,
 None,
 Timedelta('6455 days 00:00:00'),
 Timedelta('4089 days 00:00:00'),
 Timedelta('4347 days 00:00:00'),
 Timedelta('5860 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('1428 days 00:00:00'),
 Timedelta('4261 days 00:00:00'),
 Timedelta('4264 days 00:00:00'),
 None,
 Timedelta('4248 days 00:00:00'),
 None,
 Timedelta('6058 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('5886 days 00:00:00'),
 Timedelta('817 days 00:00:00'),
 Timedelta('957 days 00:00:00'),
 Timedelta('1504 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1043 days 00:00:00'),
 Timedelta('568 days 00:00:00'),
 Timedelta('4430 days 00:00:00'),
 Timedelta('1183 days 00:00:00'),
 Timedelta('853 days 00:00:00'),
 Timedelta('1226 days 00:00:00'),
 Timedelta('507 days 00:00:00'),
 None,
 Timedelta('1215 days 00:00:00'),
 Timedelta('56 days 00:00:00'),
 Timedelta('1051 days 00:00:00'),
 Timedelta('4436 days 00:00:00'),
 Timedelta('64 days 00:00:00'),
 Timedelta('1148 days 00:00:00'),
 Timedelta('372 days 00:00:00'),
 Timedelta('943 days 00:00:00'),
 Timedelta('112 days 00:00:00'),
 Timedelta('1215 days 00:00:00'),
 Timedelta('830 days 00:00:00'),
 Timedelta('960 days 00:00:00'),
 Timedelta('664 days 00:00:00'),
 None,
 None,
 Timedelta('914 days 00:00:00'),
 None,
 Timedelta('5887 days 00:00:00'),
 None,
 None,
 Timedelta('886 days 00:00:00'),
 Timedelta('1148 days 00:00:00'),
 Timedelta('1376 days 00:00:00'),
 Timedelta('543 days 00:00:00'),
 Timedelta('243 days 00:00:00'),
 Timedelta('656 days 00:00:00'),
 None,
 Timedelta('5909 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('62 days 00:00:00'),
 None,
 Timedelta('190 days 00:00:00'),
 Timedelta('393 days 00:00:00'),
 Timedelta('186 days 00:00:00'),
 Timedelta('440 days 00:00:00'),
 None,
 Timedelta('748 days 00:00:00'),
 Timedelta('444 days 00:00:00'),
 Timedelta('174 days 00:00:00'),
 Timedelta('416 days 00:00:00'),
 Timedelta('854 days 00:00:00'),
 Timedelta('4473 days 00:00:00'),
 Timedelta('823 days 00:00:00'),
 Timedelta('41 days 00:00:00'),
 Timedelta('1110 days 00:00:00'),
 Timedelta('733 days 00:00:00'),
 None,
 None,
 Timedelta('1089 days 00:00:00'),
 Timedelta('470 days 00:00:00'),
 Timedelta('1058 days 00:00:00'),
 Timedelta('15 days 00:00:00'),
 Timedelta('1302 days 00:00:00'),
 Timedelta('860 days 00:00:00'),
 Timedelta('56 days 00:00:00'),
 Timedelta('995 days 00:00:00'),
 Timedelta('413 days 00:00:00'),
 Timedelta('652 days 00:00:00'),
 Timedelta('1344 days 00:00:00'),
 Timedelta('831 days 00:00:00'),
 Timedelta('673 days 00:00:00'),
 Timedelta('1345 days 00:00:00'),
 Timedelta('419 days 00:00:00'),
 Timedelta('5916 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('6888 days 00:00:00'),
 Timedelta('663 days 00:00:00'),
 Timedelta('846 days 00:00:00'),
 Timedelta('614 days 00:00:00'),
 Timedelta('615 days 00:00:00'),
 Timedelta('99 days 00:00:00'),
 Timedelta('95 days 00:00:00'),
 Timedelta('175 days 00:00:00'),
 None,
 Timedelta('153 days 00:00:00'),
 Timedelta('1373 days 00:00:00'),
 Timedelta('767 days 00:00:00'),
 Timedelta('459 days 00:00:00'),
 Timedelta('805 days 00:00:00'),
 Timedelta('1456 days 00:00:00'),
 Timedelta('475 days 00:00:00'),
 Timedelta('717 days 00:00:00'),
 Timedelta('276 days 00:00:00'),
 Timedelta('399 days 00:00:00'),
 Timedelta('378 days 00:00:00'),
 Timedelta('788 days 00:00:00'),
 Timedelta('395 days 00:00:00'),
 Timedelta('988 days 00:00:00'),
 Timedelta('711 days 00:00:00'),
 Timedelta('711 days 00:00:00'),
 Timedelta('734 days 00:00:00'),
 Timedelta('1254 days 00:00:00'),
 Timedelta('435 days 00:00:00'),
 Timedelta('490 days 00:00:00'),
 Timedelta('629 days 00:00:00'),
 Timedelta('606 days 00:00:00'),
 Timedelta('707 days 00:00:00'),
 None,
 None,
 Timedelta('5453 days 00:00:00'),
 None,
 None,
 Timedelta('617 days 00:00:00'),
 Timedelta('617 days 00:00:00'),
 Timedelta('799 days 00:00:00'),
 Timedelta('796 days 00:00:00'),
 Timedelta('799 days 00:00:00'),
 None,
 None,
 Timedelta('9909 days 00:00:00'),
 Timedelta('4562 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1786 days 00:00:00'),
 None,
 None,
 Timedelta('365 days 00:00:00'),
 Timedelta('1975 days 00:00:00'),
 None,
 Timedelta('945 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('689 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('9346 days 00:00:00'),
 None,
 Timedelta('985 days 00:00:00'),
 Timedelta('1861 days 00:00:00'),
 Timedelta('1861 days 00:00:00'),
 None,
 Timedelta('9306 days 00:00:00'),
 Timedelta('573 days 00:00:00'),
 None,
 None,
 Timedelta('1008 days 00:00:00'),
 None,
 Timedelta('2090 days 00:00:00'),
 None,
 None,
 Timedelta('4606 days 00:00:00'),
 Timedelta('4746 days 00:00:00'),
 Timedelta('2230 days 00:00:00'),
 Timedelta('299 days 00:00:00'),
 Timedelta('13 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('556 days 00:00:00'),
 None,
 None,
 Timedelta('803 days 00:00:00'),
 Timedelta('702 days 00:00:00'),
 Timedelta('1947 days 00:00:00'),
 None,
 Timedelta('399 days 00:00:00'),
 None,
 None,
 Timedelta('9524 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('2080 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('837 days 00:00:00'),
 None,
 None,
 Timedelta('260 days 00:00:00'),
 None,
 Timedelta('9369 days 00:00:00'),
 Timedelta('5135 days 00:00:00'),
 Timedelta('440 days 00:00:00'),
 Timedelta('7141 days 00:00:00'),
 Timedelta('9393 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('727 days 00:00:00'),
 None,
 Timedelta('1498 days 00:00:00'),
 None,
 None,
 Timedelta('5059 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('135 days 00:00:00'),
 Timedelta('1855 days 00:00:00'),
 Timedelta('382 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('5009 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('2038 days 00:00:00'),
 Timedelta('5020 days 00:00:00'),
 Timedelta('911 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('2085 days 00:00:00'),
 Timedelta('2148 days 00:00:00'),
 Timedelta('9785 days 00:00:00'),
 Timedelta('5163 days 00:00:00'),
 Timedelta('1881 days 00:00:00'),
 Timedelta('4974 days 00:00:00'),
 Timedelta('2069 days 00:00:00'),
 Timedelta('1735 days 00:00:00'),
 None,
 None,
 Timedelta('986 days 00:00:00'),
 Timedelta('4772 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('1200 days 00:00:00'),
 Timedelta('2316 days 00:00:00'),
 Timedelta('2216 days 00:00:00'),
 Timedelta('4940 days 00:00:00'),
 Timedelta('988 days 00:00:00'),
 None,
 Timedelta('2134 days 00:00:00'),
 Timedelta('1288 days 00:00:00'),
 Timedelta('1736 days 00:00:00'),
 Timedelta('1736 days 00:00:00'),
 None,
 Timedelta('833 days 00:00:00'),
 Timedelta('1379 days 00:00:00'),
 Timedelta('1902 days 00:00:00'),
 None,
 Timedelta('995 days 00:00:00'),
 Timedelta('1491 days 00:00:00'),
 Timedelta('1491 days 00:00:00'),
 None,
 Timedelta('4990 days 00:00:00'),
 Timedelta('1993 days 00:00:00'),
 Timedelta('2055 days 00:00:00'),
 Timedelta('1093 days 00:00:00'),
 Timedelta('1310 days 00:00:00'),
 Timedelta('1414 days 00:00:00'),
 Timedelta('67 days 00:00:00'),
 Timedelta('365 days 00:00:00'),
 Timedelta('4675 days 00:00:00'),
 None,
 Timedelta('1005 days 00:00:00'),
 Timedelta('568 days 00:00:00'),
 None,
 Timedelta('979 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1001 days 00:00:00'),
 None,
 Timedelta('1243 days 00:00:00'),
 Timedelta('272 days 00:00:00'),
 None,
 Timedelta('719 days 00:00:00'),
 Timedelta('4866 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('2232 days 00:00:00'),
 Timedelta('837 days 00:00:00'),
 None,
 None,
 Timedelta('1414 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1481 days 00:00:00'),
 Timedelta('771 days 00:00:00'),
 Timedelta('1783 days 00:00:00'),
 Timedelta('4757 days 00:00:00'),
 None,
 None,
 Timedelta('487 days 00:00:00'),
 Timedelta('2077 days 00:00:00'),
 Timedelta('889 days 00:00:00'),
 None,
 Timedelta('9489 days 00:00:00'),
 None,
 Timedelta('1667 days 00:00:00'),
 None,
 None,
 Timedelta('4773 days 00:00:00'),
 Timedelta('1623 days 00:00:00'),
 Timedelta('610 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('4996 days 00:00:00'),
 None,
 Timedelta('1496 days 00:00:00'),
 Timedelta('276 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1158 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('553 days 00:00:00'),
 Timedelta('1254 days 00:00:00'),
 Timedelta('204 days 00:00:00'),
 Timedelta('1232 days 00:00:00'),
 Timedelta('2081 days 00:00:00'),
 None,
 None,
 Timedelta('1608 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1918 days 00:00:00'),
 Timedelta('2751 days 00:00:00'),
 None,
 Timedelta('3343 days 00:00:00'),
 Timedelta('1059 days 00:00:00'),
 Timedelta('3331 days 00:00:00'),
 Timedelta('3465 days 00:00:00'),
 Timedelta('12597 days 00:00:00'),
 Timedelta('1693 days 00:00:00'),
 Timedelta('3406 days 00:00:00'),
 None,
 None,
 Timedelta('3122 days 00:00:00'),
 Timedelta('2325 days 00:00:00'),
 Timedelta('2619 days 00:00:00'),
 None,
 Timedelta('3640 days 00:00:00'),
 Timedelta('1538 days 00:00:00'),
 None,
 Timedelta('990 days 00:00:00'),
 Timedelta('2622 days 00:00:00'),
 Timedelta('1190 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('2778 days 00:00:00'),
 Timedelta('3480 days 00:00:00'),
 Timedelta('3422 days 00:00:00'),
 None,
 Timedelta('1260 days 00:00:00'),
 Timedelta('3487 days 00:00:00'),
 Timedelta('3487 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1734 days 00:00:00'),
 Timedelta('5129 days 00:00:00'),
 Timedelta('3428 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('2843 days 00:00:00'),
 None,
 Timedelta('3745 days 00:00:00'),
 None,
 None,
 Timedelta('509 days 00:00:00'),
 None,
 Timedelta('3528 days 00:00:00'),
 Timedelta('2100 days 00:00:00'),
 None,
 Timedelta('9891 days 00:00:00'),
 Timedelta('1996 days 00:00:00'),
 None,
 Timedelta('1317 days 00:00:00'),
 Timedelta('423 days 00:00:00'),
 Timedelta('3400 days 00:00:00'),
 Timedelta('3534 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('371 days 00:00:00'),
 Timedelta('350 days 00:00:00'),
 Timedelta('1622 days 00:00:00'),
 None,
 Timedelta('4960 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 Timedelta('270 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1369 days 00:00:00'),
 Timedelta('819 days 00:00:00'),
 Timedelta('952 days 00:00:00'),
 Timedelta('941 days 00:00:00'),
 Timedelta('2900 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('1959 days 00:00:00'),
 Timedelta('1342 days 00:00:00'),
 Timedelta('2156 days 00:00:00'),
 Timedelta('358 days 00:00:00'),
 None,
 Timedelta('1386 days 00:00:00'),
 Timedelta('1908 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('4632 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1943 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('548 days 00:00:00'),
 Timedelta('2495 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('252 days 00:00:00'),
 Timedelta('275 days 00:00:00'),
 None,
 None,
 Timedelta('640 days 00:00:00'),
 Timedelta('9397 days 00:00:00'),
 Timedelta('1726 days 00:00:00'),
 Timedelta('1814 days 00:00:00'),
 None,
 None,
 Timedelta('4954 days 00:00:00'),
 Timedelta('616 days 00:00:00'),
 Timedelta('623 days 00:00:00'),
 Timedelta('2037 days 00:00:00'),
 Timedelta('658 days 00:00:00'),
 Timedelta('1727 days 00:00:00'),
 Timedelta('2420 days 00:00:00'),
 Timedelta('529 days 00:00:00'),
 Timedelta('5128 days 00:00:00'),
 None,
 None,
 Timedelta('1174 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('1287 days 00:00:00'),
 Timedelta('3774 days 00:00:00'),
 None,
 None,
 Timedelta('747 days 00:00:00'),
 Timedelta('5009 days 00:00:00'),
 Timedelta('4767 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('7865 days 00:00:00'),
 Timedelta('7916 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('1055 days 00:00:00'),
 Timedelta('1664 days 00:00:00'),
 Timedelta('350 days 00:00:00'),
 Timedelta('427 days 00:00:00'),
 Timedelta('898 days 00:00:00'),
 Timedelta('2988 days 00:00:00'),
 Timedelta('1834 days 00:00:00'),
 None,
 Timedelta('4722 days 00:00:00'),
 Timedelta('2137 days 00:00:00'),
 Timedelta('314 days 00:00:00'),
 None,
 Timedelta('537 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('444 days 00:00:00'),
 Timedelta('2605 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('5284 days 00:00:00'),
 Timedelta('1671 days 00:00:00'),
 Timedelta('1358 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('5254 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('8631 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('382 days 00:00:00'),
 Timedelta('7669 days 00:00:00'),
 Timedelta('1432 days 00:00:00'),
 None,
 None,
 Timedelta('5320 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('7204 days 00:00:00'),
 None,
 None,
 Timedelta('91 days 00:00:00'),
 Timedelta('475 days 00:00:00'),
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('7651 days 00:00:00'),
 None,
 Timedelta('918 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('438 days 00:00:00'),
 Timedelta('1580 days 00:00:00'),
 Timedelta('1144 days 00:00:00'),
 Timedelta('1059 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('317 days 00:00:00'),
 None,
 None,
 Timedelta('7477 days 00:00:00'),
 None,
 Timedelta('7330 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('7 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('8735 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('452 days 00:00:00'),
 Timedelta('532 days 00:00:00'),
 Timedelta('1637 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1421 days 00:00:00'),
 Timedelta('7281 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 Timedelta('7097 days 00:00:00'),
 Timedelta('5360 days 00:00:00'),
 None,
 None,
 Timedelta('317 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('7781 days 00:00:00'),
 None,
 None,
 Timedelta('5319 days 00:00:00'),
 None,
 None,
 Timedelta('7216 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 Timedelta('7168 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 Timedelta('788 days 00:00:00'),
 Timedelta('876 days 00:00:00'),
 None,
 None,
 Timedelta('7560 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('7486 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('50 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('13557 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1888 days 00:00:00'),
 Timedelta('720 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('7223 days 00:00:00'),
 None,
 None,
 None,
 None,
 Timedelta('7432 days 00:00:00'),
 Timedelta('7692 days 00:00:00'),
 None,
 None,
 Timedelta('778 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('13175 days 00:00:00'),
 Timedelta('2108 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('1821 days 00:00:00'),
 Timedelta('720 days 00:00:00'),
 Timedelta('15298 days 00:00:00'),
 None,
 None,
 None,
 None,
 None,
 None,
 Timedelta('203 days 00:00:00'),
 Timedelta('196 days 00:00:00'),
 None,
 None,
 Timedelta('7798 days 00:00:00'),
 None,
 None,
 Timedelta('3286 days 00:00:00'),
 None,
 None,
 Timedelta('2426 days 00:00:00'),
 None,
 None,
 None,
 Timedelta('1642 days 00:00:00'),
 None,
 Timedelta('203 days 00:00:00'),
 Timedelta('295 days 00:00:00'),
 Timedelta('234 days 00:00:00'),
 Timedelta('210 days 00:00:00'),
 Timedelta('256 days 00:00:00'),
 Timedelta('3557 days 00:00:00'),
 None,
 None,
 Timedelta('8954 days 00:00:00'),
 Timedelta('3477 days 00:00:00'),
 ...]

In [162]:
data4=data3.iloc[:,[3,4,5,6,7,17,18,19,20,21,22,23,24]]

In [163]:
data4.to_excel('C:/Users/user/Downloads/한남동.xlsx')